language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
- 3.9
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: glow-mdsol
  password:
    secure: NLsT0k/Umjvrmzuxe9V8qxiiRklUNMG03kdO6LsKhZWe7m5gUbSm8IcQqlRivEoaP83Vprk2Q6HbqxV9uP0n8ABprHfkabZPsileStE6M28NtTGwCIkCUp8245Ak7o3TVlApZRY5TZr4nZlKNM6s90iYB7OnQ8cudNDOJ1nAl/w=
  on:
    tags: true
    python: '3.7'
  distributions: sdist bdist_wheel
  skip_existing: true
